name: WhatsApp Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "22"

      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          npm install node-gtts whatsapp-web.js
          sleep 5

      - name: Compress full directory using zip
        run: |
          zip -r whatsapp-bot-full.zip .

      - name: Upload compressed project as artifact
        uses: actions/upload-artifact@v4
        with:
          name: whatsapp-bot-archive
          path: whatsapp-bot-full.zip
