name: WhatsApp Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "22"

      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          npm install node-gtts whatsapp-web.js
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "$(date)"
          git push

      - name: Run and control node script
        run: |
          node index.js &
          NODE_PID=$!
          sleep 
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
            -d '{"ref":"${{ github.ref }}"}'
          sleep 60
          kill $NODE_PID
