name: WhatsApp Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "22"
          cache: "npm"

      - name: Cache node_modules
        uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          if [ ! -d node_modules ]; then npm install; fi

      - name: Run and control node script
        run: |
          node index.js &
          NODE_PID=$!
          sleep 60
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
            -d '{"ref":"${{ github.ref }}"}'
          sleep 60
          kill $NODE_PID
